# Generated by Django 3.1.5 on 2021-01-31 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210131_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayCarsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(choices=[('BW', 'BMW'), ('AI', 'AUDI'), ('LS', 'Lexus')], default='BW', max_length=100)),
                ('car_image', models.ImageField(upload_to='images/')),
                ('ac_availability', models.BooleanField(default=True)),
                ('engine_type', models.CharField(choices=[('DL', 'DIESEL'), ('PO', 'PETROL')], max_length=100)),
                ('transmission', models.CharField(choices=[('AO', 'AUTOMATIC'), ('ML', 'MANUAL')], max_length=100)),
            ],
        ),
    ]
