# Generated by Django 3.1.5 on 2021-01-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_displaycarsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='displaycarsmodel',
            name='description',
            field=models.TextField(default='Great Car', max_length=1000),
        ),
        migrations.AlterField(
            model_name='displaycarsmodel',
            name='engine_type',
            field=models.CharField(choices=[('DL', 'DIESEL'), ('PO', 'PETROL')], default='PO', max_length=100),
        ),
        migrations.AlterField(
            model_name='displaycarsmodel',
            name='transmission',
            field=models.CharField(choices=[('AO', 'AUTOMATIC'), ('ML', 'MANUAL')], default='AO', max_length=100),
        ),
    ]
