# Generated by Django 3.1.5 on 2021-01-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210131_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='displaycarsmodel',
            name='price',
            field=models.IntegerField(default=120000, max_length=100),
        ),
    ]
