# Generated by Django 3.1.5 on 2021-01-31 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_displaycarsmodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displaycarsmodel',
            name='price',
            field=models.IntegerField(default=120000),
        ),
    ]
